templates:
- |
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: vault-agent-config
  data:
    vault-agent-config.hcl: |
      auto_auth {
        method "kubernetes" {
          mount_path = "auth/kubernetes"
          config = {
            role = "prometheus"
          }
        }
        sink "file" {
          config = {
            path = "/home/vault/config-out/.vault-token"
          }
        }
      }
