---
bases:
  - helmfile-common.yaml
---
releases:
  - name: vault-operator
    namespace: {{ .Values.vaultOperator.namespace }}
    chart: banzaicloud/vault-operator
    version: 1.10.1
    wait: true
    atomic: true
  - name: prometheus-vault-agent
    namespace:  {{ .Values.observability.namespace }}
    chart: incubator/raw
    version: 0.2.3
    condition: observability.enabled 
    atomic: true
    values:
      - values/prometheus-vault-agent.yaml
  - name: prometheus
    namespace: {{ .Values.observability.namespace }}
    chart: bitnami/kube-prometheus
    version: 4.0.1
    condition: observability.enabled 
    atomic: true
    disableValidation: true
    values:
      - values/prometheus.yaml.gotmpl
