---
bases:
  - helmfile-common.yaml

releases:
  - name: api-transaction-scheduler
    namespace: {{ requiredEnv "ORCHESTRATE_NAMESPACE" }}
    chart: helm-pegasys/core-stack-api
    atomic: true
    version: 0.5.6
    values:
      - values/common.yaml.gotmpl
      - values/common-api.yaml.gotmpl
      - values/common-multitenancy.yaml.gotmpl
      - values/api-transaction-scheduler.yaml.gotmpl
  - name: api-contract-registry
    namespace: {{ requiredEnv "ORCHESTRATE_NAMESPACE" }}
    chart: helm-pegasys/core-stack-api
    atomic: true
    version: 0.5.6
    values:
      - values/common.yaml.gotmpl
      - values/common-api.yaml.gotmpl
      - values/common-multitenancy.yaml.gotmpl
      - values/api-contract-registry.yaml.gotmpl
  - name: api-chain-registry
    namespace: {{ requiredEnv "ORCHESTRATE_NAMESPACE" }}
    chart: helm-pegasys/core-stack-api
    atomic: true
    version: 0.5.6
    values:
      - values/common.yaml.gotmpl
      - values/common-api.yaml.gotmpl
      - values/common-multitenancy.yaml.gotmpl
      - values/api-chain-registry.yaml.gotmpl
  - name: tx-crafter
    namespace: {{ requiredEnv "ORCHESTRATE_NAMESPACE" }}
    chart: helm-pegasys/core-stack-worker
    atomic: true
    version: 0.5.4
    values:
      - values/common.yaml.gotmpl
      - values/common-worker.yaml.gotmpl
      - values/common-multitenancy.yaml.gotmpl
      - values/tx-crafter.yaml.gotmpl
      - values/e2e.yaml.gotmpl
  - name: tx-signer
    namespace: {{ requiredEnv "ORCHESTRATE_NAMESPACE" }}
    chart: helm-pegasys/core-stack-worker
    atomic: true
    version: 0.5.4
    values:
      - values/common.yaml.gotmpl
      - values/common-worker.yaml.gotmpl
      - values/common-multitenancy.yaml.gotmpl
      - values/tx-signer.yaml.gotmpl
  - name: tx-sender
    namespace: {{ requiredEnv "ORCHESTRATE_NAMESPACE" }}
    chart: helm-pegasys/core-stack-worker
    atomic: true
    version: 0.5.4
    values:
      - values/common.yaml.gotmpl
      - values/common-worker.yaml.gotmpl
      - values/common-multitenancy.yaml.gotmpl
      - values/tx-sender.yaml.gotmpl
  - name: tx-listener
    namespace: {{ requiredEnv "ORCHESTRATE_NAMESPACE" }}
    chart: helm-pegasys/core-stack-worker
    atomic: true
    version: 0.5.4
    values:
      - values/common.yaml.gotmpl
      - values/common-worker.yaml.gotmpl
      - values/common-multitenancy.yaml.gotmpl
      - values/tx-listener.yaml.gotmpl
  - name: orchestrate-service-monitor
    namespace: {{ requiredEnv "OBSERVABILITY_NAMESPACE" }}
    chart: incubator/raw
    version: 0.2.3
    condition: metrics.enabled 
    atomic: true
    values:
      - orchestrate:
          namespace: {{ requiredEnv "ORCHESTRATE_NAMESPACE" }}
      - values/service-monitor.yaml 