---
bases:
  - helmfile-common.yaml

releases:
  - name: tx-crafter
    namespace: {{ requiredEnv "TARGET_NAMESPACE" }}
    chart: helm-pegasys/core-stack-worker
    atomic: true
    version: 0.5.2
    values:
      - values/tx-worker-common.yaml.gotmpl
      - values/tx-common-multitenancy.yaml.gotmpl
      - values/tx-crafter.yaml.gotmpl
  - name: tx-signer
    namespace: {{ requiredEnv "TARGET_NAMESPACE" }}
    chart: helm-pegasys/core-stack-worker
    atomic: true
    version: 0.5.2
    values:
      - values/tx-worker-common.yaml.gotmpl
      - values/tx-common-multitenancy.yaml.gotmpl
      - values/tx-signer.yaml.gotmpl
  - name: tx-sender
    namespace: {{ requiredEnv "TARGET_NAMESPACE" }}
    chart: helm-pegasys/core-stack-worker
    atomic: true
    version: 0.5.2
    values:
      - values/tx-worker-common.yaml.gotmpl
      - values/tx-common-multitenancy.yaml.gotmpl
      - values/tx-sender.yaml.gotmpl
  - name: tx-listener
    namespace: {{ requiredEnv "TARGET_NAMESPACE" }}
    chart: helm-pegasys/core-stack-worker
    atomic: true
    version: 0.5.2
    values:
      - values/tx-worker-common.yaml.gotmpl
      - values/tx-common-multitenancy.yaml.gotmpl
      - values/tx-listener.yaml.gotmpl
  - name: api-envelope-store
    namespace: {{ requiredEnv "TARGET_NAMESPACE" }}
    chart: helm-pegasys/core-stack-api
    atomic: true
    version: 0.5.2
    values:
      - values/api-common.yaml.gotmpl
      - values/tx-common-multitenancy.yaml.gotmpl
      - values/api-envelope-store.yaml.gotmpl
  - name: api-contract-registry
    namespace: {{ requiredEnv "TARGET_NAMESPACE" }}
    chart: helm-pegasys/core-stack-api
    atomic: true
    version: 0.5.2
    values:
      - values/api-common.yaml.gotmpl
      - values/tx-common-multitenancy.yaml.gotmpl
      - values/api-contract-registry.yaml.gotmpl
  - name: api-chain-registry
    namespace: {{ requiredEnv "TARGET_NAMESPACE" }}
    chart: helm-pegasys/core-stack-api
    atomic: true
    version: 0.5.2
    values:
      - values/api-common.yaml.gotmpl
      - values/tx-common-multitenancy.yaml.gotmpl
      - values/api-chain-registry.yaml.gotmpl
