---
bases:
  - helmfile-common.yaml
    
releases:
  - name: grafana
    namespace: {{ requiredEnv "OBSERVABILITY_NAMESPACE" }}
    chart: bitnami/grafana
    version: 4.2.3
    condition: metrics.enabled 
    needs:
      - {{ requiredEnv "OBSERVABILITY_NAMESPACE" }}/grafana-config
      - {{ requiredEnv "OBSERVABILITY_NAMESPACE" }}/grafana-dashboards
    atomic: true
    values:
      - values/grafana.yaml.gotmpl
  - name: grafana-config
    namespace: {{ requiredEnv "OBSERVABILITY_NAMESPACE" }}
    chart: incubator/raw
    version: 0.2.3
    condition: metrics.enabled 
    atomic: true
    values:
      - values/grafana-config.yaml.gotmpl
  - name: grafana-dashboards
    namespace: {{ requiredEnv "OBSERVABILITY_NAMESPACE" }}
    chart: incubator/raw
    version: 0.2.3
    condition: metrics.enabled 
    atomic: true
    values:
      - values/grafana-dashboards.yaml
