---
bases:
  - helmfile-common.yaml
    
releases:
  - name: vault-operator
    namespace: {{ requiredEnv "VAULT_OPERATOR_NAMESPACE" }}
    chart: banzaicloud-stable/vault-operator
    version: 1.8.1
    wait: true
    atomic: true
    values:
      - values/vault-operator.yaml
  - name: prometheus-vault-agent
    namespace:  {{ requiredEnv "OBSERVABILITY_NAMESPACE" }}
    chart: incubator/raw
    version: 0.2.3
    condition: metrics.enabled 
    atomic: true
    values:
      - values/prometheus-vault-agent.yaml
  - name: prometheus
    namespace: {{ requiredEnv "OBSERVABILITY_NAMESPACE" }}
    chart: bitnami/kube-prometheus
    version: 2.2.2
    condition: metrics.enabled 
    atomic: true
    disableValidation: true
    values:
      - values/prometheus.yaml.gotmpl
