---
bases:
  - helmfile-common.yaml

releases:
  - name: kafka
    chart: bitnami/kafka
    version: 11.8.8
    namespace: {{ requiredEnv "ORCHESTRATE_NAMESPACE" }}
    values:
      - values/kafka.yaml.gotmpl
