---
bases:
  - helmfile-common.yaml
---
releases:
  - name: kafka-{{ .Environment.Name }}
    chart: bitnami/kafka
    version: 12.7.4
    condition: kafka.enabled
    namespace: {{ .Values.kafka.namespace }}
    values:
      - values/kafka.yaml.gotmpl
{{- if .Values.vault.enabled }}
  - name: vault
    namespace: {{ .Values.vault.namespace }}
    chart: incubator/raw
    version: 0.2.3
    atomic: true
    values:
      - values/vault.yaml.gotmpl
{{- end }}
  - name: redis
    namespace: {{ .Values.redis.namespace }}
    chart: bitnami/redis
    version: 10.6.0
    atomic: true
    condition: redis.enabled
    values:
      - values/redis.yaml.gotmpl
  - name: postgresql
    namespace: {{ .Values.postgresql.namespace }}
    chart: bitnami/postgresql
    atomic: true
    condition: postgresql.enabled
    version: 8.6.12
    values:
      - values/postgresql.yaml.gotmpl
  - name: postgresql-ha
    namespace: {{ .Values.postgresqlHA.namespace }}
    chart: bitnami/postgresql-ha
    atomic: true
    condition: postgresqlHA.enabled
    version: 6.5.2
    values:
      - values/postgresql-ha.yaml.gotmpl
  - name: orchestrate
    namespace: {{ .Values.orchestrate.namespace }}
    chart: {{ .Values.orchestrate.chart.name }}
    atomic: true
    version: {{ .Values.orchestrate.chart.version }}
    needs:
      - {{ .Values.kafka.namespace }}/kafka-{{ .Environment.Name }}
      - {{ .Values.vault.namespace }}/vault
      - {{ .Values.redis.namespace }}/redis
      - {{ .Values.postgresql.namespace }}/postgresql
    values:
      - values/orchestrate.yaml.gotmpl
  - name: qkm-postgresql
    namespace: {{ .Values.qkm.namespace }}
    chart: bitnami/postgresql
    version: 10.9.5
    atomic: true
    condition: postgresql-qkm.enabled
    values:
      - values/qkm-postgres.yaml.gotmpl
  - name: quorum-key-manager
    namespace: {{ .Values.qkm.namespace }}
    chart: {{ .Values.qkm.chart.name }}
    atomic: true
    condition: qkm.enabled
    version: {{ .Values.qkm.chart.version }}
    needs:
      - {{ .Values.qkm.namespace }}/qkm-postgresql
    values:
      - values/qkm.yaml.gotmpl