---
bases:
  - helmfile-common.yaml
    
releases:
  - name: vault
    namespace: {{ requiredEnv "VAULT_NAMESPACE" }}
    chart: incubator/raw
    version: 0.2.3
    atomic: true
    values:
      - values/vault.yaml.gotmpl