---
bases:
  - helmfile-common.yaml
---
releases:
  - name: grafana
    namespace: {{ .Values.observability.namespace }}
    chart: bitnami/grafana
    version: 5.0.1
    condition: observability.enabled 
    needs:
      - {{ .Values.observability.namespace }}/grafana-config
      - {{ .Values.observability.namespace }}/grafana-dashboards
    atomic: true
    values:
      - values/grafana.yaml.gotmpl
  - name: grafana-config
    namespace: {{ .Values.observability.namespace }}
    chart: incubator/raw
    version: 0.2.3
    condition: observability.enabled 
    atomic: true
    values:
      - values/grafana-config.yaml.gotmpl
  - name: grafana-dashboards
    namespace: {{ .Values.observability.namespace }}
    chart: incubator/raw
    version: 0.2.3
    condition: observability.enabled 
    atomic: true
    values:
      - values/grafana-dashboards.yaml.gotmpl
