---
bases:
  - helmfile-common.yaml
---
releases:
  - name: orchestrate
    namespace: {{ .Values.orchestrate.namespace }}
    chart: {{ .Values.orchestrate.chart.name }}
    atomic: true
    version: {{ .Values.orchestrate.chart.version }}    
    values:
      - values/orchestrate.yaml.gotmpl
