observability:
  enabled: true

kafka:
  resources:
    requests:
      memory: "1Gi"
    limits:
      memory: "2Gi"
  persistence:
    enabled: false

zookeeper:
  resources:
    requests:
      memory: "512Mi"
    limits:
      memory: "1Gi"
  persistence:
    enabled: false

postgresql:
  persistence:
    enabled: false