observability:
  enabled: false

qkm:
  auth:
    apikey:
      enabled: true
      file: "/apikey/sample.csv"
    tls:
      enabled: false
    oidc:
      enabled: false


kafka:
  logRetentionHours: 1
  resources:
    requests:
      memory: "1Gi"
    limits:
      memory: "2Gi"

zookeeper:
  resources:
    requests:
      memory: "512Mi"
    limits:
      memory: "1Gi"

