orchestrate:
  replicaCount: 3
  global:
    environment:
      MULTI_TENANCY_ENABLED: true
      TOPIC_TX_DECODED: staging-tx-decoded
      TOPIC_TX_RECOVER: staging-tx-recover
      TOPIC_TX_SENDER: staging-tx-sender
      DB_DATABASE: orchestrate_staging
      KAFKA_URL: orchestrate.servicebus.windows.net:9093
    environmentSecrets:
      AUTH_API_KEY: with-key

observability:
  enabled: true
drop:
  enabled: false

vault:
  replicaCount: 3

qkm:
  url: https://staging-qkm.ops.consensys.net

nodeSelector:
  enabled: false