orchestrate:
  replicaCount: 3
  global:
    environment:
      MULTI_TENANCY_ENABLED: true
    environmentSecrets:
      AUTH_API_KEY: with-key

observability:
  enabled: false

vault:
  replicaCount: 3

qkm:
  url: https://qa-qkm.ops.consensys.net