orchestrate:
  replicaCount: 3
  global:
    environment:
      MULTI_TENANCY_ENABLED: true
      DB_DATABASE: orchestrate_staging
    environmentSecrets:
      AUTH_API_KEY: with-key

observability:
  enabled: true
drop:
  enabled: false

vault:
  replicaCount: 3

qkm:
  url: https://staging-qkm.ops.consensys.net