---
helmDefaults:
  verify: false
  wait: true
  timeout: 600
  recreatePods: false
  force: false
environments:
  observability:
    values:
      - ../environments/observability.yaml
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami/
  - name: incubator
    url: https://charts.helm.sh/incubator

    
releases:
  - name: prometheus
    namespace: {{ requiredEnv "TARGET_NAMESPACE" }}
    chart: bitnami/kube-prometheus
    version: 2.2.2
    atomic: true
    values:
      - prometheus/values.yaml
  - name: prometheus-service-monitor
    namespace: {{ requiredEnv "TARGET_NAMESPACE" }}
    chart: incubator/raw
    version: 0.2.3
    atomic: true
    values:
      - prometheus/service-monitor.yaml 
  - name: grafana
    namespace: {{ requiredEnv "TARGET_NAMESPACE" }}
    chart: bitnami/grafana
    version: 3.4.5
    atomic: true
    values:
      - grafana/values.yaml 
  - name: grafana-config
    namespace: {{ requiredEnv "TARGET_NAMESPACE" }}
    chart: incubator/raw
    version: 0.2.3
    atomic: true
    values:
      - grafana/config.yaml 
