{
 "title": "Orchestrate",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "query_result(orchestrate_healthcheck_status)"
   },
   {
    "name": "service",
    "query": "orchestrate_http_open_connections{namespace=\"$namespace\"}"
   },
   {
    "name": "pod",
    "query": "kube_pod_info{exported_pod=~\"$service.+\"}"
   }
  ]
 },
 "panels": [
  { "title": "Stack", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Deployment and Statefulset replicas",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{exported_namespace=\"$namespace\",deployment=~\"orchestrate-api|orchestrate-key-manager|orchestrate-tx-listener|orchestrate-tx-sender\"}",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  { "title": "Transaction monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Pre-sent average latency (ms)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status,prev_status) (increase(orchestrate_transaction_scheduler_job_latency_seconds_sum[1m])) / sum by (status,prev_status) (increase(orchestrate_transaction_scheduler_job_latency_seconds_count[1m]))*1000",
     "legendFormat": "{{prev_status}} to {{status}}"
    }
   ]
  },
  {
   "title": "Post-sent average latency (s)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status,prev_status) (rate(orchestrate_transaction_scheduler_mined_latency_seconds_sum[1m])) / sum by (status,prev_status) (rate(orchestrate_transaction_scheduler_mined_latency_seconds_count[1m]))",
     "legendFormat": "{{prev_status}} to {{status}}"
    }
   ]
  },
  {
   "title": "% success and failure over the last hour",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(\n  (sum(rate(orchestrate_transaction_scheduler_mined_latency_seconds_count{status=\"MINED\"}[15m])) or vector(0))\n  +\n  (sum(rate(orchestrate_transaction_scheduler_job_latency_seconds_count{status=\"STORED\"}[15m])) or vector(0))\n)\n/\n(\n  (sum(rate(orchestrate_transaction_scheduler_mined_latency_seconds_count{status=\"MINED\"}[15m])) or vector(0))\n  +\n  (sum(rate(orchestrate_transaction_scheduler_job_latency_seconds_count{status=~\"STORED|FAILED\"}[15m])) or vector(0))\n)*100",
     "legendFormat": "Sucess"
    },
    {
     "expr": "(sum(rate(orchestrate_transaction_scheduler_job_latency_seconds_count{status=\"FAILED\"}[15m])) or vector(0))\n/\n(\n  (sum(rate(orchestrate_transaction_scheduler_mined_latency_seconds_count{status=\"MINED\"}[15m])) or vector(0))\n  +\n  (sum(rate(orchestrate_transaction_scheduler_job_latency_seconds_count{status=~\"STORED|FAILED\"}[15m])) or vector(0))\n)*100",
     "legendFormat": "Fail"
    }
   ]
  },
  {
   "title": "Number of block processed per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(orchestrate_transaction_listener_current_block{namespace=\"$namespace\"}[1m])",
     "legendFormat": "{{ chain_uuid }}"
    }
   ]
  },
  {
   "title": "Transaction status rate per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status,prev_status) (rate(orchestrate_transaction_scheduler_mined_latency_seconds_count{status=\"MINED\",namespace=\"$namespace\"}[1m]))",
     "legendFormat": "{{prev_status}} to {{status}}"
    },
    {
     "expr": "sum by (status,prev_status) (rate(orchestrate_transaction_scheduler_job_latency_seconds_count{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "{{prev_status}} to {{status}}"
    }
   ]
  },
  {
   "title": "Transaction status rate per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status,prev_status) (rate(orchestrate_transaction_scheduler_mined_latency_seconds_count{status=\"MINED\",namespace=\"$namespace\"}[1m]))",
     "legendFormat": "{{prev_status}} to {{status}}"
    }
   ]
  },
  { "title": "$service - HTTP metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Unreachable dependencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (check) (orchestrate_healthcheck_status{service=\"$service\",pod=~\"$pod\",namespace=\"$namespace\"})",
     "legendFormat": "{{check}}"
    }
   ]
  },
  {
   "title": "Incoming open connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_service) (orchestrate_http_open_connections{service=\"$service\",exported_service!~\"healthcheck@healthcheck|prometheus@prometheus|swagger@swagger\",namespace=\"$namespace\"})",
     "legendFormat": "{{ exported_service }}"
    }
   ]
  },
  {
   "title": "Error logs",
   "type": "logs",
   "gridPos": { "h": 24, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "{job=\"$namespace/$service\"} |~ \"error|warn|fatal\""
    }
   ]
  },
  {
   "title": "Request/s by method and status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_service,method,code) ( rate(orchestrate_http_requests_total{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\",exported_service!~\"healthcheck@healthcheck|prometheus@prometheus|swagger@swagger\"}[1m]) )",
     "legendFormat": "{{exported_service}}[{{method}}][{{ code }}]"
    }
   ]
  },
  {
   "title": "HTTP error codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(orchestrate_http_requests_total{code!~\"^(1|2).*\",namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\",exported_service!=\"healthcheck@healthcheck|prometheus@prometheus\"}[1m]))\nby (code,service,namespace)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Average request duration by method and status (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "((sum by (exported_service,method,code) (rate(orchestrate_http_requests_latency_seconds_sum{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\",exported_service!~\"healthcheck@healthcheck|prometheus@prometheus|swagger@swagger\"}[1m])))\n/\n(sum by (exported_service,method,code) (rate(orchestrate_http_requests_latency_seconds_count{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\",exported_service!~\"healthcheck@healthcheck|prometheus@prometheus|swagger@swagger\"}[1m]))))*1000",
     "legendFormat": "{{exported_service}}[{{method}}][{{ code }}]"
    }
   ]
  },
  {
   "title": "Percentiles requests latency (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(orchestrate_http_requests_latency_seconds_bucket{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\",exported_service!~\"healthcheck@healthcheck|prometheus@prometheus|swagger@swagger\"}[5m])) by (le,exported_service))*1000",
     "legendFormat": "{{exported_service}}[90th]"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(orchestrate_http_requests_latency_seconds_bucket{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\",exported_service!~\"healthcheck@healthcheck|prometheus@prometheus|swagger@swagger\"}[5m])) by (le,exported_service))*1000",
     "legendFormat": "{{exported_service}}[95th]"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(orchestrate_http_requests_latency_seconds_bucket{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\",exported_service!~\"healthcheck@healthcheck|prometheus@prometheus|swagger@swagger\"}[5m])) by (le,exported_service))*1000",
     "legendFormat": "{{exported_service}}[99th]"
    }
   ]
  }
 ]
}