apiVersion: v1
kind: Pod
metadata:
  name: vegeta
spec:
  restartPolicy: Never
  volumes:
    - name: config-volume
      configMap:
        name: vegeta-configmap
  containers:
    - name: vegeta1
      image: peterevans/vegeta:6.9.1
      command: ["/bin/sh", "-c"]
      volumeMounts:
        - name: config-volume
          mountPath: /vegeta
      args: ["cd /vegeta; cat test | vegeta attack -format=http -duration=1m30s -rate=500/s -connections 75 | vegeta report"]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vegeta-configmap
data:
  test: |
    POST http://orchestrate-api:8081/transactions/send
    x-api-key: with-key
    Content-Type: application/json
    @body.json
  body.json: |
     {
      "chain": "besu",
      "params": {
        "methodSignature": "increment(uint256)",
        "args": [1],
        "to": "0x42699a7612a82f1d9c36148af9c77354759b210b",
        "gasPrice": "0x0",
        "gas": 25000,
        "oneTimeKey": true,
        "contractName": "increment",
        "contractTag": "v1.0.0"
        }
      }
---
